kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-role
  namespace: {{NAMESPACE}}
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
  namespace: helm-ns
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: helm-ns
roleRef:
  kind: Role
  name: tiller-role
  apiGroup: rbac.authorization.k8s.io
